// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoIoT.Models;

namespace ProyectoIoT.Migrations
{
    [DbContext(typeof(UsuariosContext))]
    [Migration("20201215163240_AgregandoUsuarios")]
    partial class AgregandoUsuarios
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("ProyectoIot.Models.Dispositivo", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CambiarEstado")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DuenioID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Potencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temperatura")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Temporizar")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("DuenioID");

                    b.ToTable("Dispositivos");
                });

            modelBuilder.Entity("ProyectoIot.Models.Usuario", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(6);

                    b.Property<string>("Duenio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoIot.Models.Dispositivo", b =>
                {
                    b.HasOne("ProyectoIot.Models.Usuario", "Duenio")
                        .WithMany("Dispositivos")
                        .HasForeignKey("DuenioID");
                });
#pragma warning restore 612, 618
        }
    }
}
